export type HelpGuideKey = 'student' | 'faculty' | 'admin' | 'documentation';

export interface HelpScenario {
    id: string;
    category: string;
    title: string;
    summary: string;
    instructions: string[];
    tips?: string[];
    keywords: string[];
    useCaseRef: string;
}

export interface HelpGuide {
    key: HelpGuideKey;
    title: string;
    subtitle: string;
    description: string;
    scenarioCountLabel: string;
    scenarios: HelpScenario[];
}

const studentScenarios: HelpScenario[] = [
    {
        id: 'register-account',
        category: 'Introduction',
        title: 'Register for a Student Account',
        summary: 'Create your account and activate it through email verification.',
        instructions: [
            'Open registration and enter your email, full name, and password.',
            'Use a strong password with at least 8 characters.',
            'Submit and confirm your email using the verification link.',
            'Return to login and sign in to open your dashboard.',
        ],
        tips: ['If email is already registered, use Forgot Password.'],
        keywords: ['register', 'signup', 'verification', 'account creation'],
        useCaseRef: 'UC-S1',
    },
    {
        id: 'login-system',
        category: 'Introduction',
        title: 'Log In to the System',
        summary: 'Access assignments, grades, and schedule from your dashboard.',
        instructions: [
            'Go to login and provide your email and password.',
            'Submit credentials and wait for redirect.',
            'Confirm you are routed to your student dashboard.',
            'Review active courses and pending tasks.',
        ],
        tips: ['Multiple failed attempts can temporarily lock login.'],
        keywords: ['login', 'signin', 'dashboard', 'access'],
        useCaseRef: 'UC-S2',
    },
    {
        id: 'view-assignments',
        category: 'Assignments',
        title: 'View and Filter Assignments',
        summary: 'Find published assignments by course, status, and due date.',
        instructions: [
            'Open My Assignments from the top navigation.',
            'Use filters for course and status to reduce noise.',
            'Sort by due date when planning daily work.',
            'Open details to review rubric and allowed files.',
        ],
        keywords: ['assignments', 'filter', 'sort', 'due date'],
        useCaseRef: 'UC-S3',
    },
    {
        id: 'submit-assignment',
        category: 'Submissions',
        title: 'Submit an Assignment',
        summary: 'Upload or paste code, run public tests, and submit for grading.',
        instructions: [
            'Open assignment details and review requirements.',
            'Upload your file(s) or paste code into the editor.',
            'Run public tests and inspect output.',
            'Submit for grading and confirm timestamped success message.',
        ],
        tips: ['Late submissions are blocked after due date.'],
        keywords: ['submit', 'upload', 'public tests', 'attempts'],
        useCaseRef: 'UC-S4',
    },
    {
        id: 'view-grades-feedback',
        category: 'Grades',
        title: 'View Grades and Feedback',
        summary: 'Open scoring details, rubric points, and instructor comments.',
        instructions: [
            'Open My Grades.',
            'Select a submission from the graded list.',
            'Review rubric breakdown and test outcomes.',
            'Download PDF if you need a full report copy.',
        ],
        keywords: ['grades', 'feedback', 'rubric', 'report'],
        useCaseRef: 'UC-S5',
    },
    {
        id: 'download-grade-report',
        category: 'Grades',
        title: 'Download Full Grade Report',
        summary: 'Export your progress as a complete PDF report.',
        instructions: [
            'Go to My Progress.',
            'Click Download Full Report.',
            'Wait for generation to complete.',
            'Save file for advising or records.',
        ],
        keywords: ['progress', 'pdf', 'grade report'],
        useCaseRef: 'UC-S6',
    },
    {
        id: 'assignment-schedule',
        category: 'Schedule and Planning',
        title: 'Track Assignment Schedule',
        summary: 'Use calendar views to manage upcoming deadlines.',
        instructions: [
            'Open Schedule page.',
            'Switch month, week, or list view.',
            'Select a date to inspect due items.',
            'Prioritize items with the shortest remaining time.',
        ],
        keywords: ['calendar', 'schedule', 'deadline'],
        useCaseRef: 'UC-S7',
    },
    {
        id: 'join-course-code',
        category: 'Course Access',
        title: 'Join a Course Using Invite or Code',
        summary: 'Enroll in a course using instructor invite links or enrollment code.',
        instructions: [
            'Open Courses and choose Join Course.',
            'Paste invite code or accept email invitation link.',
            'Verify course appears in your active course list.',
            'Open the course dashboard and sync announcements.',
        ],
        keywords: ['join course', 'invite', 'enroll', 'course code'],
        useCaseRef: 'HELP-S1',
    },
    {
        id: 'resubmit-before-deadline',
        category: 'Submissions',
        title: 'Resubmit Before Deadline',
        summary: 'Replace earlier attempts while attempts remain and deadline is open.',
        instructions: [
            'Open your assignment submission page.',
            'Review current attempt count and max attempts.',
            'Upload revised files and rerun tests.',
            'Submit new attempt before due time.',
        ],
        tips: ['The newest accepted submission is used for grading unless course policy says otherwise.'],
        keywords: ['resubmit', 'attempt count', 'revision'],
        useCaseRef: 'HELP-S2',
    },
    {
        id: 'understand-failed-tests',
        category: 'Submissions',
        title: 'Interpret Failed Public Tests',
        summary: 'Read failed test output and identify mismatch causes quickly.',
        instructions: [
            'Open test run output panel.',
            'Compare expected output vs your output exactly.',
            'Check edge cases, formatting, and data types.',
            'Re-run tests after each focused fix.',
        ],
        keywords: ['failed tests', 'debug', 'output mismatch'],
        useCaseRef: 'HELP-S3',
    },
    {
        id: 'request-regrade',
        category: 'Grades',
        title: 'Request Grade Review or Regrade',
        summary: 'Submit a professional regrade request with evidence.',
        instructions: [
            'Open graded submission details.',
            'Collect rubric criteria where you believe points were missed.',
            'Send regrade request with concise explanation and references.',
            'Track request status in notifications or course messages.',
        ],
        tips: ['Be specific and objective; avoid generic appeals.'],
        keywords: ['regrade', 'grade appeal', 'review request'],
        useCaseRef: 'HELP-S4',
    },
    {
        id: 'notifications-setup',
        category: 'Schedule and Planning',
        title: 'Configure Deadline Notifications',
        summary: 'Set reminders to avoid missing assignments.',
        instructions: [
            'Open Settings from your profile menu.',
            'Navigate to notifications section.',
            'Enable assignment reminders and grading updates.',
            'Choose email or in-app preference by event type.',
        ],
        keywords: ['notifications', 'reminders', 'deadlines'],
        useCaseRef: 'HELP-S5',
    },
    {
        id: 'group-assignment-workflow',
        category: 'Collaboration',
        title: 'Work on Group Assignment Submission',
        summary: 'Coordinate one final submission for group-based tasks.',
        instructions: [
            'Confirm your group membership in course tools.',
            'Decide submission owner and integration plan.',
            'Validate final files against assignment checklist.',
            'Submit once and notify teammates immediately.',
        ],
        keywords: ['group assignment', 'team submission', 'collaboration'],
        useCaseRef: 'HELP-S6',
    },
    {
        id: 'academic-integrity-student',
        category: 'Integrity',
        title: 'Avoid Academic Integrity Violations',
        summary: 'Keep submissions original and appropriately cited.',
        instructions: [
            'Review course collaboration and AI policy before coding.',
            'Do not copy from classmates or public repositories.',
            'Cite permitted references when required by policy.',
            'Submit your own tested and understood solution.',
        ],
        keywords: ['integrity', 'plagiarism', 'policy', 'original work'],
        useCaseRef: 'HELP-S7',
    },
    {
        id: 'fix-upload-errors',
        category: 'Technical Issues',
        title: 'Resolve Upload and Submission Errors',
        summary: 'Fix common issues like unsupported file type and oversized uploads.',
        instructions: [
            'Check allowed extensions listed on assignment.',
            'Confirm total upload size is within limit.',
            'Compress or remove non-required artifacts.',
            'Retry upload on a stable network connection.',
        ],
        tips: ['If issue persists, capture screenshot and contact support before deadline.'],
        keywords: ['upload error', 'file too large', 'unsupported format'],
        useCaseRef: 'HELP-S8',
    },
];

const facultyScenarios: HelpScenario[] = [
    {
        id: 'create-assignment',
        category: 'Assignment Design',
        title: 'Create a New Assignment',
        summary: 'Build assignment details, rubric, and tests in draft mode.',
        instructions: [
            'Open Assignments and click Create New Assignment.',
            'Add details, language, due date, attempts, and optional starter files.',
            'Define rubric and ensure total weights equal 100%.',
            'Add public and private tests before saving draft.',
        ],
        keywords: ['create assignment', 'rubric', 'tests', 'draft'],
        useCaseRef: 'UC-F1',
    },
    {
        id: 'publish-assignment',
        category: 'Assignment Design',
        title: 'Publish an Assignment',
        summary: 'Validate completeness and release assignment to students.',
        instructions: [
            'Open draft assignment and preview settings.',
            'Check rubric, tests, and due date validity.',
            'Click Publish Assignment.',
            'Confirm visibility and student notifications.',
        ],
        keywords: ['publish', 'assignment visibility', 'release'],
        useCaseRef: 'UC-F2',
    },
    {
        id: 'view-submissions',
        category: 'Grading Workflow',
        title: 'View Submission Queue',
        summary: 'Track pending, graded, and overridden submissions.',
        instructions: [
            'Open Grading and select assignment.',
            'Review student, attempt, status, and score columns.',
            'Apply filters for pending or score ranges.',
            'Sort list to prioritize review order.',
        ],
        keywords: ['submissions', 'queue', 'pending'],
        useCaseRef: 'UC-F3',
    },
    {
        id: 'grade-submission',
        category: 'Grading Workflow',
        title: 'Grade a Submission',
        summary: 'Review code and tests, then submit score and feedback.',
        instructions: [
            'Open submission from queue.',
            'Inspect code, test output, and rubric values.',
            'Add inline or summary feedback.',
            'Submit final grade and publish result.',
        ],
        keywords: ['grade', 'feedback', 'rubric scoring'],
        useCaseRef: 'UC-F4',
    },
    {
        id: 'override-grade',
        category: 'Grading Workflow',
        title: 'Override an Auto-Generated Grade',
        summary: 'Apply manual score adjustment with mandatory justification.',
        instructions: [
            'Open graded submission and click Override Score.',
            'Adjust criterion or total score values.',
            'Enter detailed justification text.',
            'Save override and verify Overridden badge.',
        ],
        tips: ['Students can view override reasons, so keep rationale precise.'],
        keywords: ['override', 'manual grade', 'justification'],
        useCaseRef: 'UC-F5',
    },
    {
        id: 'export-grades',
        category: 'Reports and Analytics',
        title: 'Export Course Grades',
        summary: 'Generate Canvas CSV, Excel, or PDF exports.',
        instructions: [
            'Open Reports and pick course.',
            'Select Export Grades and choose format.',
            'Set filters and date range.',
            'Generate and download file.',
        ],
        keywords: ['export grades', 'canvas csv', 'excel'],
        useCaseRef: 'UC-F6',
    },
    {
        id: 'assignment-analytics',
        category: 'Reports and Analytics',
        title: 'Analyze Assignment Performance',
        summary: 'Inspect distribution, pass rates, and difficulty indicators.',
        instructions: [
            'Open assignment analytics view.',
            'Review score histogram and timeline.',
            'Inspect low pass-rate tests and common errors.',
            'Use insights to tune future assignments.',
        ],
        keywords: ['analytics', 'distribution', 'pass rates'],
        useCaseRef: 'UC-F7',
    },
    {
        id: 'course-settings',
        category: 'Course Management',
        title: 'Manage Course Settings',
        summary: 'Update policies, grading scale, and announcements preferences.',
        instructions: [
            'Open course and navigate to Course Settings.',
            'Adjust grading scale and late policy values.',
            'Update collaboration and announcement preferences.',
            'Save and verify applied changes.',
        ],
        keywords: ['course settings', 'grading scale', 'late policy'],
        useCaseRef: 'UC-F8',
    },
    {
        id: 'build-clear-rubric',
        category: 'Assignment Design',
        title: 'Create a Clear Rubric Students Can Follow',
        summary: 'Design criteria that align with learning outcomes and tests.',
        instructions: [
            'Define 3 to 6 measurable criteria for the assignment.',
            'Set criterion descriptions with specific expectations.',
            'Balance criterion weights to reflect priorities.',
            'Preview rubric as student before publishing.',
        ],
        keywords: ['rubric design', 'criteria', 'assessment'],
        useCaseRef: 'HELP-F1',
    },
    {
        id: 'manage-deadline-extensions',
        category: 'Course Management',
        title: 'Grant Deadline Extensions for Specific Students',
        summary: 'Handle accommodations while preserving auditability.',
        instructions: [
            'Open assignment settings and locate override rules.',
            'Add student-specific due date extension.',
            'Document reason in course notes if policy requires.',
            'Notify student and confirm updated deadline appears.',
        ],
        keywords: ['extension', 'accommodation', 'due date override'],
        useCaseRef: 'HELP-F2',
    },
    {
        id: 'bulk-feedback-patterns',
        category: 'Grading Workflow',
        title: 'Use Feedback Templates for Common Mistakes',
        summary: 'Speed up grading while maintaining quality comments.',
        instructions: [
            'Identify repeat error patterns across submissions.',
            'Create reusable feedback snippets per rubric criterion.',
            'Personalize one line for each student context.',
            'Apply templates consistently during grading pass.',
        ],
        keywords: ['feedback templates', 'grading speed', 'comments'],
        useCaseRef: 'HELP-F3',
    },
    {
        id: 'handle-plagiarism-flags',
        category: 'Integrity and Appeals',
        title: 'Review and Escalate Plagiarism Flags',
        summary: 'Investigate similarity alerts before applying penalties.',
        instructions: [
            'Open flagged submission report.',
            'Compare suspicious segments with sources or peers.',
            'Check course policy and evidence threshold.',
            'Escalate to integrity workflow with documented findings.',
        ],
        keywords: ['plagiarism', 'integrity case', 'similarity flag'],
        useCaseRef: 'HELP-F4',
    },
    {
        id: 'regrade-after-test-fix',
        category: 'Grading Workflow',
        title: 'Regrade After Updating Broken Test Cases',
        summary: 'Apply fair scoring if a faulty test affected outcomes.',
        instructions: [
            'Correct failing test definition in assignment config.',
            'Run validation against sample correct solution.',
            'Trigger regrade for affected submissions.',
            'Communicate update transparently to class.',
        ],
        keywords: ['regrade', 'test fix', 'fairness'],
        useCaseRef: 'HELP-F5',
    },
    {
        id: 'prepare-lms-export-ready',
        category: 'Reports and Analytics',
        title: 'Prepare LMS-Ready Grade Exports',
        summary: 'Validate formatting before importing into LMS gradebook.',
        instructions: [
            'Export using LMS-specific template (Canvas CSV).',
            'Verify required columns and score scales.',
            'Run a small test import in staging if possible.',
            'Publish final export to LMS gradebook.',
        ],
        keywords: ['lms export', 'canvas import', 'gradebook'],
        useCaseRef: 'HELP-F6',
    },
    {
        id: 'monitor-struggling-students',
        category: 'Reports and Analytics',
        title: 'Identify and Support Struggling Students',
        summary: 'Use analytics to target interventions early.',
        instructions: [
            'Filter analytics for low score or missed submission patterns.',
            'Review criterion-level weaknesses.',
            'Send targeted guidance and office-hour invites.',
            'Track improvement in subsequent assignments.',
        ],
        keywords: ['at-risk students', 'intervention', 'analytics'],
        useCaseRef: 'HELP-F7',
    },
    {
        id: 'publish-announcement-batch',
        category: 'Course Management',
        title: 'Send Effective Assignment Announcements',
        summary: 'Reduce confusion with clear pre-deadline communication.',
        instructions: [
            'Draft concise announcement with deliverables and deadline.',
            'Include allowed files and grading criteria reminders.',
            'Post announcement with enough lead time.',
            'Pin or repeat reminder 24 hours before due date.',
        ],
        keywords: ['announcement', 'communication', 'deadline reminder'],
        useCaseRef: 'HELP-F8',
    },
];

const adminScenarios: HelpScenario[] = [
    {
        id: 'manage-users',
        category: 'User Administration',
        title: 'Manage User Accounts',
        summary: 'Edit role, status, and access safely for users.',
        instructions: [
            'Open User Management and find user record.',
            'Update profile, role, or account status.',
            'Save and validate changes.',
            'Confirm action appears in audit history.',
        ],
        keywords: ['users', 'roles', 'deactivate', 'admin'],
        useCaseRef: 'UC-A1',
    },
    {
        id: 'view-audit-logs',
        category: 'Security and Audit',
        title: 'View Audit Logs',
        summary: 'Investigate actions, failures, and suspicious behavior.',
        instructions: [
            'Open Audit Logs and apply date filters.',
            'Filter by user, action type, and status.',
            'Search by keywords such as failed login.',
            'Export evidence as CSV if needed.',
        ],
        keywords: ['audit logs', 'security events', 'investigation'],
        useCaseRef: 'UC-A2',
    },
    {
        id: 'system-settings',
        category: 'Platform Configuration',
        title: 'Configure System Settings',
        summary: 'Change global security, upload, and grading defaults.',
        instructions: [
            'Open System Settings and select category.',
            'Apply changes and resolve validation warnings.',
            'Confirm restart-required settings if prompted.',
            'Record change rationale for operations history.',
        ],
        keywords: ['settings', 'security', 'feature flags'],
        useCaseRef: 'UC-A3',
    },
    {
        id: 'programming-languages',
        category: 'Languages and Sandbox',
        title: 'Manage Supported Programming Languages',
        summary: 'Configure runtimes and validation tests for language support.',
        instructions: [
            'Open Languages and review runtime entries.',
            'Add name, version, extension, command, and image.',
            'Run sample code validation test.',
            'Enable language for assignment authoring.',
        ],
        keywords: ['languages', 'runtime', 'docker image'],
        useCaseRef: 'UC-A4',
    },
    {
        id: 'system-health',
        category: 'Monitoring and Reliability',
        title: 'Monitor System Health',
        summary: 'Track API, queue, sandbox, and infrastructure metrics.',
        instructions: [
            'Open System Dashboard.',
            'Inspect CPU, memory, latency, and error rates.',
            'Drill into alerts and identify root cause.',
            'Adjust thresholds and alert channels.',
        ],
        keywords: ['health', 'monitoring', 'alerts'],
        useCaseRef: 'UC-A5',
    },
    {
        id: 'system-reports',
        category: 'Data and Compliance',
        title: 'Generate System Reports',
        summary: 'Export operational and security reports for stakeholders.',
        instructions: [
            'Open Reports and select report type.',
            'Set date range, format, and chart options.',
            'Generate report and monitor processing status.',
            'Download when ready or from email notification.',
        ],
        keywords: ['reports', 'compliance', 'export'],
        useCaseRef: 'UC-A6',
    },
    {
        id: 'onboard-faculty-batch',
        category: 'User Administration',
        title: 'Bulk Onboard Faculty and Assistants',
        summary: 'Create instructor accounts efficiently with correct roles.',
        instructions: [
            'Prepare CSV with name, email, and role columns.',
            'Upload in User Management bulk import.',
            'Review validation warnings before confirm.',
            'Send onboarding instructions after import completion.',
        ],
        keywords: ['bulk import', 'faculty onboarding', 'roles'],
        useCaseRef: 'HELP-A1',
    },
    {
        id: 'incident-response-auth',
        category: 'Security and Audit',
        title: 'Respond to Suspicious Login Activity',
        summary: 'Contain account abuse and protect platform access quickly.',
        instructions: [
            'Filter audit logs for failed and unusual logins.',
            'Temporarily lock compromised accounts.',
            'Force password reset and token revocation.',
            'Document incident timeline and mitigation actions.',
        ],
        keywords: ['incident response', 'failed logins', 'account compromise'],
        useCaseRef: 'HELP-A2',
    },
    {
        id: 'tune-sandbox-limits',
        category: 'Languages and Sandbox',
        title: 'Tune Sandbox Resource Limits',
        summary: 'Balance execution safety with assignment performance needs.',
        instructions: [
            'Review timeout and memory failures by language.',
            'Adjust CPU/memory/time limits conservatively.',
            'Run regression test submissions in staging.',
            'Deploy changes and monitor failure trend.',
        ],
        keywords: ['sandbox', 'timeouts', 'resource limits'],
        useCaseRef: 'HELP-A3',
    },
    {
        id: 'configure-backups',
        category: 'Data and Compliance',
        title: 'Verify Backup and Recovery Readiness',
        summary: 'Ensure data recovery objectives are testable and current.',
        instructions: [
            'Check backup job status and retention policy.',
            'Run periodic restore test in staging.',
            'Verify integrity of restored records.',
            'Document RPO/RTO results for compliance.',
        ],
        keywords: ['backup', 'recovery', 'restore test', 'retention'],
        useCaseRef: 'HELP-A4',
    },
    {
        id: 'email-delivery-ops',
        category: 'Platform Configuration',
        title: 'Fix Email Delivery and Notification Issues',
        summary: 'Diagnose SMTP and template issues that block notifications.',
        instructions: [
            'Validate SMTP host, credentials, and sender domain.',
            'Send test email from settings panel.',
            'Check bounce logs and suppression lists.',
            'Update templates and retry impacted notifications.',
        ],
        keywords: ['email config', 'smtp', 'notification delivery'],
        useCaseRef: 'HELP-A5',
    },
    {
        id: 'integration-tokens',
        category: 'Integrations and Maintenance',
        title: 'Rotate API and Integration Credentials',
        summary: 'Reduce risk with scheduled credential rotation.',
        instructions: [
            'Inventory active integration keys and owners.',
            'Create replacement credentials in secure vault.',
            'Deploy and verify new keys in integrations.',
            'Revoke old keys and log completion date.',
        ],
        keywords: ['api keys', 'token rotation', 'integration security'],
        useCaseRef: 'HELP-A6',
    },
    {
        id: 'capacity-planning',
        category: 'Monitoring and Reliability',
        title: 'Plan Capacity for Peak Submission Windows',
        summary: 'Prevent outages during deadline spikes.',
        instructions: [
            'Review historical submission peaks by hour and course.',
            'Scale workers and queue consumers ahead of peak.',
            'Load-test critical submission and grading paths.',
            'Monitor live metrics and auto-scale thresholds.',
        ],
        keywords: ['capacity planning', 'peak load', 'worker scaling'],
        useCaseRef: 'HELP-A7',
    },
    {
        id: 'data-retention-policy',
        category: 'Data and Compliance',
        title: 'Apply Data Retention and Purge Policy',
        summary: 'Manage long-term storage and privacy compliance.',
        instructions: [
            'Define retention windows for submissions, logs, and reports.',
            'Configure scheduled cleanup jobs.',
            'Verify legal hold exclusions before purge.',
            'Generate monthly purge compliance report.',
        ],
        keywords: ['retention', 'purge', 'privacy', 'compliance'],
        useCaseRef: 'HELP-A8',
    },
];

const documentationScenarios: HelpScenario[] = [
    {
        id: 'doc-product-overview',
        category: 'Executive and Product Overview',
        title: 'Kriterion Product Overview (Current Implementation)',
        summary: 'Kriterion is an automated grading platform for programming assignments with role-based workflows for students, faculty, and admins.',
        instructions: [
            'Primary audience: Students submit programming work, Faculty design/grade assignments, Administrators govern system operations.',
            'Core value proposition: faster grading cycles, rubric consistency, transparent feedback, and auditable score changes.',
            'Primary capabilities: assignment authoring, test-case driven grading, report generation, language management, and security auditing.',
            'Documentation sources in repository: README, PROJECT_SUMMARY, IMPLEMENTATION_STATUS, DEPLOYMENT, ENVIRONMENT, COMMANDS, S3_INTEGRATION_SUMMARY.',
        ],
        keywords: ['overview', 'stakeholder summary', 'business value', 'scope'],
        useCaseRef: 'DOC-1',
    },
    {
        id: 'doc-problem-and-goals',
        category: 'Executive and Product Overview',
        title: 'Problem Statement and Delivery Goals',
        summary: 'The project addresses slow/manual grading, inconsistent rubric application, and limited visibility into submission quality trends.',
        instructions: [
            'Pain points addressed: delayed feedback, repetitive grading overhead, and low traceability of grade adjustments.',
            'Target outcomes: shorter grading turnaround, consistent rubric scoring, and role-specific analytics visibility.',
            'Operational quality goals: secure execution isolation, reliable file handling, auditable user actions, and clear deployment runbooks.',
            'Adoption criteria for customers/teachers: complete end-to-end assignment lifecycle and export-ready reporting workflows.',
        ],
        keywords: ['problem statement', 'goals', 'metrics', 'success criteria'],
        useCaseRef: 'DOC-2',
    },
    {
        id: 'doc-architecture-blueprint',
        category: 'System Architecture',
        title: 'End-to-End Runtime Architecture',
        summary: 'The platform uses a modular web architecture with separate UI, API, worker, persistence, queue, and sandbox layers.',
        instructions: [
            'Frontend: Next.js 14 App Router with TypeScript and Tailwind for role-based UI flows.',
            'Backend: FastAPI service exposing versioned routes under /api/v1 with JWT-protected endpoints.',
            'Data and queue: PostgreSQL for transactional records, Redis + Celery for asynchronous execution and grading workloads.',
            'Execution and storage: isolated sandbox container for code runs and S3/local storage for submission artifacts.',
        ],
        keywords: ['architecture', 'components', 'data flow', 'celery', 'sandbox'],
        useCaseRef: 'DOC-3',
    },
    {
        id: 'doc-tech-stack-justification',
        category: 'System Architecture',
        title: 'Technology Stack and Rationale',
        summary: 'Current stack balances developer speed, maintainability, and production readiness for an academic SaaS workflow.',
        instructions: [
            'UI stack: Next.js + React + TypeScript + Tailwind for rapid role-specific pages and strong client typing.',
            'API stack: FastAPI + Pydantic + SQLAlchemy + Alembic for typed contracts, clean schema evolution, and robust ORM usage.',
            'Asynchronous stack: Celery + Redis to decouple grading execution from synchronous HTTP request latency.',
            'Packaging and operations: Docker Compose for local parity; Vercel/Render/Redis Cloud/S3 documented for production.',
        ],
        keywords: ['tech stack', 'trade-offs', 'design decisions', 'rationale'],
        useCaseRef: 'DOC-4',
    },
    {
        id: 'doc-role-capabilities',
        category: 'Functional Documentation',
        title: 'Role-Based Capabilities Matrix',
        summary: 'Access and actions are segmented by Student, Faculty, Assistant, and Admin responsibilities.',
        instructions: [
            'Student role: account access, assignment submission, schedule tracking, grades, and feedback review.',
            'Faculty role: course/assignment management, rubric/test configuration, grading, overrides, and reporting.',
            'Assistant role: grading and submission review workflows with constrained teaching-assistant scope.',
            'Admin role: user lifecycle management, audit visibility, language/runtime configuration, and system-level settings.',
        ],
        keywords: ['rbac', 'permissions', 'roles', 'capability matrix'],
        useCaseRef: 'DOC-5',
    },
    {
        id: 'doc-assignment-lifecycle',
        category: 'Functional Documentation',
        title: 'Assignment Lifecycle (Draft to Graded)',
        summary: 'The core workflow starts with assignment design and ends with graded feedback and export-ready reporting.',
        instructions: [
            'Faculty creates draft assignment with rubric criteria, weights, and public/private test cases.',
            'Assignment is published and made visible to eligible students based on course enrollment.',
            'Student submits code, optional pre-checks run, and submission enters autograding pipeline.',
            'Faculty can review, override with justification, and publish final scores and feedback artifacts.',
        ],
        keywords: ['workflow', 'assignment lifecycle', 'status transitions', 'grading flow'],
        useCaseRef: 'DOC-6',
    },
    {
        id: 'doc-api-contracts',
        category: 'API and Integration Documentation',
        title: 'API Surface (Implemented Router Domains)',
        summary: 'Versioned API routes are organized by domain and documented through OpenAPI endpoints.',
        instructions: [
            'Primary domains: auth, students, faculty, admin, courses, assignments, submissions, reports, settings, languages, notifications, ai-detection.',
            'OpenAPI documentation endpoints: /api/docs and /api/redoc on backend service.',
            'Health and service liveness endpoints: /health and root endpoint / for basic diagnostics.',
            'Contract strategy: typed request/response schemas with centralized routing in backend/app/api/v1/api.py.',
        ],
        keywords: ['api contract', 'openapi', 'request response', 'error handling'],
        useCaseRef: 'DOC-7',
    },
    {
        id: 'doc-lms-integration',
        category: 'API and Integration Documentation',
        title: 'LMS Integration and Export Paths',
        summary: 'Reporting workflows support LMS-aligned grade export patterns, including Canvas-compatible outputs.',
        instructions: [
            'Report endpoints include assignment/course/student summaries and grade export operations.',
            'Canvas CSV export is documented as a faculty-facing output path in reports workflow.',
            'Export files are positioned for LMS ingestion with student identifiers and score fields.',
            'Operational validation includes format checks before distribution to institutional LMS owners.',
        ],
        keywords: ['canvas', 'lms integration', 'grade export', 'csv mapping'],
        useCaseRef: 'DOC-8',
    },
    {
        id: 'doc-data-model',
        category: 'Data and Security Documentation',
        title: 'Data Model Overview',
        summary: 'Persistent entities support users, courses, assignments, rubrics, submissions, execution results, and audit evidence.',
        instructions: [
            'Core entities include User, Course, Enrollment, Assignment, Rubric components, TestSuite/TestCase, Submission, and AuditLog.',
            'Relational ownership maps students to enrollments, assignments to courses, and submissions to student-assignment pairs.',
            'Submission file records track storage path (S3/local), hash metadata, and upload lifecycle context.',
            'Audit-relevant tables preserve operational history for grade changes, user administration, and security actions.',
        ],
        keywords: ['data model', 'entities', 'relationships', 'schema'],
        useCaseRef: 'DOC-9',
    },
    {
        id: 'doc-security-controls',
        category: 'Data and Security Documentation',
        title: 'Security Controls Implemented',
        summary: 'Security posture combines authentication controls, authorization boundaries, auditability, and execution isolation.',
        instructions: [
            'Authentication and authorization: JWT access/refresh strategy with role-based endpoint protection.',
            'Credential protections: hashed passwords, login throttling controls, and configurable token lifetimes.',
            'Runtime protections: sandboxed code execution, request ID tracing middleware, and centralized exception handling.',
            'Governance controls: audit logs, CORS restrictions, and environment-driven security configurations.',
        ],
        keywords: ['security', 'jwt', 'sandbox isolation', 'audit log', 'incident response'],
        useCaseRef: 'DOC-10',
    },
    {
        id: 'doc-privacy-retention',
        category: 'Data and Security Documentation',
        title: 'Data Privacy and Retention Baseline',
        summary: 'The project defines sensitive data handling through role-based access, storage controls, and operational governance.',
        instructions: [
            'User profile, submissions, and grading artifacts are available strictly within role permissions and ownership context.',
            'Storage strategy supports S3-backed object storage with path scoping per assignment/student/submission.',
            'Audit and reporting data retention is documented for administrative oversight and incident investigation.',
            'Institutional deployments can enforce local retention windows through operations policy and cleanup jobs.',
        ],
        keywords: ['privacy', 'retention', 'purge policy', 'data governance'],
        useCaseRef: 'DOC-11',
    },
    {
        id: 'doc-deployment-runbook',
        category: 'Deployment and Operations',
        title: 'Production Deployment Model',
        summary: 'Documented deployment topology uses Vercel (frontend), Render (backend/workers), Redis Cloud, PostgreSQL, and AWS S3.',
        instructions: [
            'Infrastructure prerequisites and variable setup are defined in DEPLOYMENT.md.',
            'Backend service set includes API, Celery worker, and Celery beat for scheduled/background tasks.',
            'Frontend deployment requires NEXT_PUBLIC_API_URL pointed to backend /api/v1.',
            'Post-deploy verification includes login, assignment visibility, submission flow, and report access checks.',
        ],
        keywords: ['deployment', 'runbook', 'rollback', 'production release'],
        useCaseRef: 'DOC-12',
    },
    {
        id: 'doc-env-configuration',
        category: 'Deployment and Operations',
        title: 'Environment Configuration Reference (Implemented)',
        summary: 'Runtime behavior is strongly driven by environment variables for security, storage, queueing, and execution limits.',
        instructions: [
            'Required variables include DATABASE_URL, SECRET_KEY, CORS origins, and public API URL for frontend.',
            'Operational variables include Celery broker/backend URLs, sandbox resource limits, and upload constraints.',
            'Optional cloud variables include AWS credentials, region, bucket, and USE_S3_STORAGE toggle.',
            'Reference source of truth: backend/app/core/config.py and ENVIRONMENT.md.',
        ],
        keywords: ['environment variables', 'configuration', 'secrets', 'ops'],
        useCaseRef: 'DOC-13',
    },
    {
        id: 'doc-monitoring-slo',
        category: 'Deployment and Operations',
        title: 'Operational Monitoring and Reliability Signals',
        summary: 'The platform exposes application-level health and structured logs for runtime diagnostics and performance tracing.',
        instructions: [
            'Health endpoint provides service liveness and environment metadata for uptime checks.',
            'Request middleware emits request ID and process-time headers for traceability and latency review.',
            'Celery queues and Redis usage provide asynchronous throughput indicators for grading workloads.',
            'Logs and alert thresholds should focus on auth failures, queue lag, sandbox errors, and API error rates.',
        ],
        keywords: ['monitoring', 'slo', 'alerts', 'operations'],
        useCaseRef: 'DOC-14',
    },
    {
        id: 'doc-testing-strategy',
        category: 'Quality Assurance and Testing',
        title: 'Testing Strategy and Verification Paths',
        summary: 'Quality assurance combines automated backend tests with scenario-level workflow validation.',
        instructions: [
            'Automated backend tests exist under backend/tests with authentication and service-level coverage entry points.',
            'Regression-critical journeys: login, role routing, assignment publishing, submission, grading, and report retrieval.',
            'Command references for execution and troubleshooting are centralized in COMMANDS.md and Make targets.',
            'Pre-release checks should include API contract availability and role-protected route behavior.',
        ],
        keywords: ['testing strategy', 'coverage', 'ci', 'quality gates'],
        useCaseRef: 'DOC-15',
    },
    {
        id: 'doc-uat-checklist',
        category: 'Quality Assurance and Testing',
        title: 'Teacher/Customer UAT Checklist',
        summary: 'Acceptance validation should confirm practical educational workflows, not only technical endpoint behavior.',
        instructions: [
            'Student UAT: registration/login, assignment discovery, submission flow, grade and feedback visibility.',
            'Faculty UAT: assignment setup, rubric/test integrity, grading override, and export/report generation.',
            'Admin UAT: user role management, audit log access, language configuration, and settings persistence.',
            'Sign-off criteria: no blocker defects in end-to-end grading path and expected report outputs match policy.',
        ],
        keywords: ['uat', 'acceptance testing', 'teacher validation', 'customer signoff'],
        useCaseRef: 'DOC-16',
    },
    {
        id: 'doc-user-guides',
        category: 'User-Facing Documentation',
        title: 'Role-Based User Guide Coverage',
        summary: 'Help content now includes student, faculty, and admin scenario libraries with searchable categories and expandable details.',
        instructions: [
            'Student guide covers account setup, submissions, scheduling, grade review, and integrity expectations.',
            'Faculty guide covers assignment design, grading workflows, policy handling, and analytics.',
            'Admin guide covers operations, security, language/runtime governance, and compliance-oriented controls.',
            'Guide UX supports keyword search, topic grouping, and direct link-to-expanded detail behavior.',
        ],
        keywords: ['user manual', 'role guide', 'tutorial', 'knowledge base'],
        useCaseRef: 'DOC-17',
    },
    {
        id: 'doc-support-playbook',
        category: 'User-Facing Documentation',
        title: 'Support and Troubleshooting Playbook',
        summary: 'Operational support should use reproducible diagnostics tied to command and log references.',
        instructions: [
            'First-line diagnostics: service status, container logs, database readiness, and Redis connectivity checks.',
            'Functional triage: authentication failures, upload issues, queue execution delays, and report generation errors.',
            'Recovery references: make commands for restart, logs, migrations, and shell access into backend/db containers.',
            'Escalation requires request IDs, timestamp, user role, and reproducible steps from affected workflow.',
        ],
        keywords: ['support', 'troubleshooting', 'playbook', 'escalation'],
        useCaseRef: 'DOC-18',
    },
    {
        id: 'doc-release-notes',
        category: 'Delivery and Handover',
        title: 'Release Notes and Change Impact Format',
        summary: 'Each release should communicate technical changes and role-level operational impact.',
        instructions: [
            'Document additions by module: frontend pages/components, backend endpoints/services, and migration updates.',
            'List behavior changes affecting Student, Faculty, Admin, and Assistant user journeys.',
            'Include configuration or environment changes required for deployment continuity.',
            'Maintain historical release archive for traceable support and audit readiness.',
        ],
        keywords: ['release notes', 'change log', 'versioning', 'impact analysis'],
        useCaseRef: 'DOC-19',
    },
    {
        id: 'doc-handover-package',
        category: 'Delivery and Handover',
        title: 'Final Handover Package (Developer-to-Customer/Teacher)',
        summary: 'The complete package includes product, architecture, operations, security, QA, and support documentation for long-term ownership.',
        instructions: [
            'Core documents: README, DEPLOYMENT, ENVIRONMENT, COMMANDS, PROJECT_SUMMARY, IMPLEMENTATION_STATUS, and feature guides in Help.',
            'Technical handoff: API route map, storage/queue architecture, sandbox behavior, and environment variable matrix.',
            'Operational handoff: run/stop/recover commands, monitoring signals, security controls, and backup/retention policy alignment.',
            'Delivery sign-off: validated UAT journeys, known limitations, and prioritized roadmap for post-delivery enhancements.',
        ],
        keywords: ['handover', 'client delivery', 'teacher expectations', 'documentation package'],
        useCaseRef: 'DOC-20',
    },
];

export const helpGuides: HelpGuide[] = [
    {
        key: 'student',
        title: 'Student Guide',
        subtitle: 'Assignment and learning workflows',
        description: 'Step-by-step instructions for account setup, assignments, submissions, grades, planning, and common issues.',
        scenarioCountLabel: '15 scenarios',
        scenarios: studentScenarios,
    },
    {
        key: 'faculty',
        title: 'Faculty Guide',
        subtitle: 'Teaching and grading workflows',
        description: 'Practical instructions for assignment design, grading operations, analytics, communication, and policy handling.',
        scenarioCountLabel: '16 scenarios',
        scenarios: facultyScenarios,
    },
    {
        key: 'admin',
        title: 'Admin Guide',
        subtitle: 'Platform operations and governance',
        description: 'Operational guidance for security, configuration, reliability, integrations, and compliance reporting.',
        scenarioCountLabel: '14 scenarios',
        scenarios: adminScenarios,
    },
    {
        key: 'documentation',
        title: 'Project Documentation Guide',
        subtitle: 'What teachers and customers expect from developers',
        description: 'Comprehensive documentation standards covering architecture, quality, deployment, support, and handover.',
        scenarioCountLabel: '20 topics',
        scenarios: documentationScenarios,
    },
];

export const helpGuideMap: Record<HelpGuideKey, HelpGuide> = {
    student: helpGuides[0],
    faculty: helpGuides[1],
    admin: helpGuides[2],
    documentation: helpGuides[3],
};

export const isHelpGuideKey = (value: string): value is HelpGuideKey => {
    return value === 'student' || value === 'faculty' || value === 'admin' || value === 'documentation';
};
